---
language: perl
sudo: required
services:
  - docker

before_script:
  - make -f ci/Makefile

script:
  - make -f ci/Makefile test

after_script:
  - make -f ci/Makefile clean

env:
  matrix:
    - ZOOKEEPER_VERSION=3.3.6       PERL_VERSION=5.10.1
    - ZOOKEEPER_VERSION=3.3.6       PERL_VERSION=5.10.1-threaded
    - ZOOKEEPER_VERSION=3.3.6       PERL_VERSION=5.24.0
    - ZOOKEEPER_VERSION=3.3.6       PERL_VERSION=5.24.0-threaded
    - ZOOKEEPER_VERSION=3.4.6       PERL_VERSION=5.10.1
    - ZOOKEEPER_VERSION=3.4.6       PERL_VERSION=5.10.1-threaded
    - ZOOKEEPER_VERSION=3.4.6       PERL_VERSION=5.24.0
    - ZOOKEEPER_VERSION=3.4.6       PERL_VERSION=5.24.0-threaded
    - ZOOKEEPER_VERSION=3.4.8       PERL_VERSION=5.10.1
    - ZOOKEEPER_VERSION=3.4.8       PERL_VERSION=5.10.1-threaded
    - ZOOKEEPER_VERSION=3.4.8       PERL_VERSION=5.24.0
    - ZOOKEEPER_VERSION=3.4.8       PERL_VERSION=5.24.0-threaded
    - ZOOKEEPER_VERSION=3.5.2-alpha PERL_VERSION=5.10.1
    - ZOOKEEPER_VERSION=3.5.2-alpha PERL_VERSION=5.10.1-threaded
    - ZOOKEEPER_VERSION=3.5.2-alpha PERL_VERSION=5.24.0
    - ZOOKEEPER_VERSION=3.5.2-alpha PERL_VERSION=5.24.0-threaded

